-- DROP DATABASE uengine;
CREATE DATABASE uengine CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

DROP USER 'uengine'@'localhost' ;
CREATE USER 'uengine'@'localhost' IDENTIFIED BY 'uengine';
GRANT ALL PRIVILEGES ON *.* TO 'uengine'@'localhost';
FLUSH PRIVILEGES;

USE uengine;

DROP TABLE IF EXISTS uengine.CL_AUTHORITIES;
DROP TABLE IF EXISTS uengine.CL_USER;
DROP TABLE IF EXISTS uengine.CL_USER_LEVEL;

CREATE TABLE IF NOT EXISTS uengine.CL_USER_LEVEL (
  LEVEL             SMALLINT NOT NULL,
  LEVEL_NM          VARCHAR(30) NOT NULL,
  PRIMARY KEY (LEVEL)
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8;

INSERT INTO uengine.CL_USER_LEVEL (LEVEL, LEVEL_NM) VALUES (1, '1등급');
INSERT INTO uengine.CL_USER_LEVEL (LEVEL, LEVEL_NM) VALUES (2, '2등급');
INSERT INTO uengine.CL_USER_LEVEL (LEVEL, LEVEL_NM) VALUES (3, '3등급');
INSERT INTO uengine.CL_USER_LEVEL (LEVEL, LEVEL_NM) VALUES (4, '4등급');
INSERT INTO uengine.CL_USER_LEVEL (LEVEL, LEVEL_NM) VALUES (5, '5등급');


CREATE TABLE IF NOT EXISTS uengine.CL_USER (
  ID                bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'User iD',
  EMAIL             varchar(255) DEFAULT NULL COMMENT 'E-mail',
  PASSWD            varchar(255) DEFAULT NULL COMMENT '비밀번호',
  ENABLED           BOOLEAN NOT NULL DEFAULT FALSE,
  NM                varchar(255) DEFAULT NULL COMMENT '이름(Full Name)',
  DESCRIPTION       longtext COMMENT '비고',
  REG_DT            timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  UPD_DT            TIMESTAMP NOT NULL DEFAULT 0 COMMENT '수정일',
  LEVEL             smallint(6) NOT NULL DEFAULT '5' COMMENT '등급',
  FIRST_NAME    VARCHAR(255) DEFAULT NULL COMMENT '이름',
  LAST_NAME     VARCHAR(255) DEFAULT NULL COMMENT '성',
  ORGANIZATION  VARCHAR(255) DEFAULT NULL COMMENT '회',
  OFFICE_PHONE         VARCHAR(255) DEFAULT NULL COMMENT '회사 연락처',
  COUNTRY       CHAR(2) DEFAULT NULL COMMENT '국가코드',
  ADDRESS1      LONGTEXT COMMENT '주소1',
  ADDRESS2      LONGTEXT COMMENT '주소2',
  CITY          VARCHAR(255) DEFAULT NULL COMMENT '도시',
  STATE         VARCHAR(255) DEFAULT NULL COMMENT '행정구역',
  ZIP           VARCHAR(255) DEFAULT NULL COMMENT '우편번호',
  PHONE         VARCHAR(255) DEFAULT NULL COMMENT '연락처',
  TAXID         VARCHAR(255) DEFAULT NULL COMMENT '택스ID',
  FOREIGN KEY (LEVEL) REFERENCES uengine.CL_USER_LEVEL(LEVEL),
  PRIMARY KEY (ID),
  UNIQUE KEY (EMAIL)
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8;

INSERT INTO uengine.CL_USER (ID, EMAIL, PASSWD, NM, DESCRIPTION, UPD_DT, ENABLED, LEVEL , COUNTRY)
VALUES (1, 'support@uengine.co.kr', 'MEVd1+d7s2DoZt8mgx+1kg==', '시스템 관리자', null, CURRENT_TIMESTAMP, 1, 1 , 'KR');

INSERT INTO uengine.CL_USER (ID, EMAIL, PASSWD, NM, DESCRIPTION, UPD_DT, ENABLED, LEVEL , COUNTRY)
VALUES (2, 'demo@uengine.co.kr', 'MEVd1+d7s2DoZt8mgx+1kg==', '데모', null, CURRENT_TIMESTAMP, 1, 1 , 'KR');


CREATE TABLE IF NOT EXISTS uengine.CL_AUTHORITIES (
  ID              BIGINT NOT NULL AUTO_INCREMENT,
  USER_ID         BIGINT NOT NULL,
  AUTHORITY       VARCHAR(100) NOT NULL DEFAULT 'ROLE_USER',
  AUTHORITY_NM    VARCHAR(100) NOT NULL DEFAULT '사용자',
  PRIMARY KEY (ID),
  FOREIGN KEY(USER_ID) references uengine.CL_USER(ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8;

INSERT INTO uengine.CL_AUTHORITIES ( USER_ID , AUTHORITY, AUTHORITY_NM) VALUES (1 , 'ROLE_ADMIN', '관리자');
INSERT INTO uengine.CL_AUTHORITIES ( USER_ID , AUTHORITY, AUTHORITY_NM) VALUES (2 , 'ROLE_USER', '사용자');


CREATE TABLE IF NOT EXISTS uengine.CL_REGISTE (
  id               INT(11) NOT NULL AUTO_INCREMENT,
  user_id          BIGINT NOT NULL,
  token            VARCHAR(255) NOT NULL,
  registration     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY (token),
  PRIMARY KEY (ID)
)
  ENGINE=InnoDB DEFAULT CHARSET=utf8;